# ░█████╗░███████╗██╗░░██╗██╗██╗░░░░░██╗░░░░░░██████╗███████╗██╗░░░██╗███████╗███╗░░██╗████████╗░██████╗
# ██╔══██╗██╔════╝██║░██╔╝██║██║░░░░░██║░░░░░██╔════╝██╔════╝██║░░░██║██╔════╝████╗░██║╚══██╔══╝██╔════╝
# ███████║█████╗░░█████═╝░██║██║░░░░░██║░░░░░╚█████╗░█████╗░░╚██╗░██╔╝█████╗░░██╔██╗██║░░░██║░░░╚█████╗░
# ██╔══██║██╔══╝░░██╔═██╗░██║██║░░░░░██║░░░░░░╚═══██╗██╔══╝░░░╚████╔╝░██╔══╝░░██║╚████║░░░██║░░░░╚═══██╗
# ██║░░██║██║░░░░░██║░╚██╗██║███████╗███████╗██████╔╝███████╗░░╚██╔╝░░███████╗██║░╚███║░░░██║░░░██████╔╝
# ╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝╚══════╝╚══════╝╚═════╝░╚══════╝░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░░░╚═╝░░░╚═════╝░
#
# Автор: anton_flame (Telegram: anton_flame)
#
# Формат использовония Hex: &#
# Удобный сайт для получения Hex цветов: https://htmlcolorcodes.com/

first-event:
  # Настройки 1 ивента "Киллер дня"
  settings:
    # Включена ли работа ивента
    enabled: true
    # Время начала ивента (МСК)
    start-time: "10:00"
    # Время окончания ивента (МСК)
    stop-time: "22:00"
    # Команды, которые будут выполнены после окончания ивента для победителя
    reward-commands:
      - "points give %player% 1000"
      - "eco give %player% 10000"
  messages:
    # Сообщение при начале ивента
    started:
      - ""
      - "&a&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ НАЧАТ!"
      - ""
      - "&fИгрок, который убьет больше всех игроков до &622:00&f,"
      - "&fполучит &61000 поинтов &fи &610000 монет&f!"
      - ""
    # Сообщение при окончании ивента, если имелись участники
    stopped-have-members:
      - ""
      - "&c&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fПобедитель ивента: &6%player%"
      - "&fОн убил &6%kills% &fигроков"
      - ""
    # Сообщение при окончании ивента, если участников не было
    stopped-no-members:
      - ""
      - "&c&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fК сожалению, в ивенте никто не поучаствовал :("
      - ""

# Настройки 2 ивента "Килл рандомного игрока"
second-event:
  settings:
    # Включена ли работа ивента
    enabled: true
    # Время начала ивента (МСК)
    start-time: "14:00"
    # Время окончания ивента, если жертву никто не смог убить (МСК)
    stop-time: "18:00"
    # Команды, которые будут выполнены после окончания ивента для победителя
    reward-commands-victim-killed:
      - "points give %player% 1500"
      - "eco give %player% 15000"
    # Настройка награды жертвы, если ее никто не убил
    reward-victim-not-killed:
      # Включена ли работа награды
      enabled: true
      # Команды, которые будут выполнены после окончания ивента для жертвы
      commands:
        - "points give %player% 1500"
        - "eco give %player% 15000"
  messages:
    # Сообщение при начале ивента
    started:
      - ""
      - "&a&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ НАЧАТ!"
      - ""
      - "&fИгрок, который убьет игрока &6%player% &fдо &618:00"
      - "&fполучит &61500 поинтов &fи &615000 монет&f!"
      - ""
    # Сообщение при окончании ивента, если жертву убили
    stopped-victim-killed:
      - ""
      - "&c&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fЖертва была убита игроком &6%player%&f!"
      - ""
    # Сообщение при окончании ивента, если жертву никто не смог убить
    stopped-victim-not-killed:
      - ""
      - "&c&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fЖертву никто не смог убить!"
      - "&fИ поэтому она получила награду в размере &61500 поинтов &fи &615000 монет&f."
      - ""
# Сообщения плагина
messages:
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Сообщение при недостатке прав
  no-permission: "&cУ вас недостаточно прав!"
  # Сообщение при попытке начать ивент, который уже был начат
  event-already-started: "&cЭтот ивент уже был начат!"
  # Сообщение при попытке окончить ивент, который не был начат
  event-not-started: "&cЭтот ивент еще не был начат!"
  # Сообщение при начале первого ивента
  first-event-started: "&fВы принудительно начали первый ивент!"
  # Сообщение при окончании первого ивента
  first-event-stopped: "&fВы принудительно окончили первый ивент!"
  # Сообщение при начале второго ивента
  second-event-started: "&fВы принудительно начали второй ивент!"
  # Сообщение при окончании второго ивента
  second-event-stopped: "&fВы принудительно окончили второй ивент!"
  # Хелп-сообщение
  help:
    - ""
    - "&fПомощь по плагину &6AFKillEvents&f:"
    - ""
    - "&6/afkillevents reload &f- перезагрузить конфигурацию"
    - "&6/afkillevents start first &f- начать первый ивент принудительно"
    - "&6/afkillevents stop first &f- окончить первый ивент принудительно"
    - "&6/afkillevents start second &f- начать второй ивент принудительно"
    - "&6/afkillevents stop second &f- окончить второй ивент принудительно"
    - ""
