# ░█████╗░███████╗██╗░░██╗██╗██╗░░░░░██╗░░░░░░██████╗███████╗██╗░░░██╗███████╗███╗░░██╗████████╗░██████╗
# ██╔══██╗██╔════╝██║░██╔╝██║██║░░░░░██║░░░░░██╔════╝██╔════╝██║░░░██║██╔════╝████╗░██║╚══██╔══╝██╔════╝
# ███████║█████╗░░█████═╝░██║██║░░░░░██║░░░░░╚█████╗░█████╗░░╚██╗░██╔╝█████╗░░██╔██╗██║░░░██║░░░╚█████╗░
# ██╔══██║██╔══╝░░██╔═██╗░██║██║░░░░░██║░░░░░░╚═══██╗██╔══╝░░░╚████╔╝░██╔══╝░░██║╚████║░░░██║░░░░╚═══██╗
# ██║░░██║██║░░░░░██║░╚██╗██║███████╗███████╗██████╔╝███████╗░░╚██╔╝░░███████╗██║░╚███║░░░██║░░░██████╔╝
# ╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝╚══════╝╚══════╝╚═════╝░╚══════╝░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░░░╚═╝░░░╚═════╝░
# Автор: anton_flame (ТГК: https://t.me/anton_flame_coder)

# Формат использовония Hex: &#
# Удобный сайт для получения Hex цветов: https://htmlcolorcodes.com/

first-event:
  # Настройки 1 ивента "Киллер дня"
  settings:
    # Включена ли работа ивента
    enabled: true
    # Время начала ивента (МСК)
    start-time: "10:00"
    # Время окончания ивента (МСК)
    stop-time: "22:00"
    # Сколько максимально может один игрок убить другого игрока раз?
    max-kills: 3
    # Настройка боссбара
    bossbar:
      enabled: true
      text: "&fИвент &6«Киллер дня» &fактивен &7| &fОкончание в &622:00 по МСК"
      color: "YELLOW"
      style: "SOLID"
    # Награды для победителя ивента (награда выбирается случайно из всех. Если не нужна случайная награда, оставьте 1 награду и впишите в нее все нужные команды)
    rewards:
      1:
        - "eco give %player% 1000"
        - "p give %player% 100"
      2:
        - "eco give %player% 2000"
        - "p give %player% 200"
      3:
        - "eco give %player% 3000"
        - "p give %player% 300"
  messages:
    # Сообщение при начале ивента
    started:
      - ""
      - "&a&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ НАЧАТ!"
      - ""
      - "&fИгрок, который убьет больше всех игроков до &622:00&f,"
      - "&fполучит награду!"
      - ""
    # Сообщение при окончании ивента, если имелись участники
    stopped-have-members:
      - ""
      - "&c&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fПобедитель ивента: &6%player%"
      - "&fОн убил &6%kills% &fигроков"
      - ""
    # Сообщение при окончании ивента, если участников не было
    stopped-no-members:
      - ""
      - "&c&lИВЕНТ «КИЛЛЕР ДНЯ» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fК сожалению, в ивенте никто не поучаствовал :("
      - ""
    # Сообщение киллеру, если он убил игрока максимальное количество раз
    max-kills: "&cВы убили игрока %player% уже 3 раза!"

second-event:
  # Настройки 2 ивента "Килл рандомного игрока"
  settings:
    # Включена ли работа ивента
    enabled: true
    # Время начала ивента (МСК)
    start-time: "14:00"
    # Время окончания ивента, если жертву никто не смог убить (МСК)
    stop-time: "18:00"
    # Настройка боссбара
    bossbar:
      enabled: true
      text: "&fИвент &6«Килл рандомного игрока» &fактивен &7| &fЖертва: &6%victim% &7| &fОкончание в &618:00 по МСК"
      color: "YELLOW"
      style: "SOLID"
    # Награды для победителя ивента (награда выбирается случайно из всех. Если не нужна случайная награда, оставьте 1 награду и впишите в нее все нужные команды)
    rewards-for-winner:
      1:
        - "eco give %player% 15000"
        - "p give %player% 1500"
      2:
        - "eco give %player% 20000"
        - "p give %player% 2000"
      3:
        - "eco give %player% 25000"
        - "p give %player% 2500"
    # Настройка награды жертвы, если ее никто не убил
    reward-victim-not-killed:
      # Включена ли работа награды
      enabled: true
      # Награды для жертвы, если ее никто не смог убить (награда выбирается случайно из всех. Если не нужна случайная награда, оставьте 1 награду и впишите в нее все нужные команды)
      rewards:
        1:
          - "eco give %player% 5000"
          - "p give %player% 500"
        2:
          - "eco give %player% 10000"
          - "p give %player% 1000"
        3:
          - "eco give %player% 15000"
          - "p give %player% 1500"
    # Время, через которое жертва может перезайти и новая жертва выбрана не будет (секунды)
    victim-timeout: 300
  messages:
    # Сообщение при начале ивента
    started:
      - ""
      - "&a&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ НАЧАТ!"
      - ""
      - "&fИгрок, который убьет игрока &6%player% &fдо &618:00"
      - "&fполучит награду!"
      - ""
    # Сообщение при окончании ивента, если жертву убили
    stopped-victim-killed:
      - ""
      - "&c&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fЖертва была убита игроком &6%player%&f!"
      - ""
    # Сообщение при окончании ивента, если жертву никто не смог убить
    stopped-victim-not-killed:
      - ""
      - "&c&lИВЕНТ «КИЛЛ РАНДОМНОГО ИГРОКА» БЫЛ ОКОНЧЕН!"
      - ""
      - "&fЖертву никто не смог убить!"
      - "&fИ поэтому она получила награду."
      - ""
    # Сообщение, когда жертва вышла с сервера
    victim-quit:
      - ""
      - "&fЖертва &6%victim% &fвышла с сервера!"
      - "&fЕсли через &65 минут &fона не перезайдет, то выберется новая!"
      - ""
    # Сообщение, когда жертва перезашла на сервер
    victim-rejoin:
      - ""
      - "&fЖертва &6%victim% &fперезашла на сервер!"
      - "&fПоэтому новая жертва выбрана не будет"
      - ""
    # Сообщение, когда была выбрана новая жертва
    new-victim:
      - ""
      - "&fСтарая жертва &6%old_victim% &fне перезашла на сервер!"
      - "&fПоэтому была выбрана новая - &6%new_victim%"
      - ""

# Сообщения плагина
messages:
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Сообщение при недостатке прав
  no-permission: "&cУ Вас недостаточно прав!"
  # Сообщение при попытке начать ивент, который уже был начат
  event-already-started: "&cЭтот ивент уже был начат!"
  # Сообщение при попытке окончить ивент, который не был начат
  event-not-started: "&cЭтот ивент еще не был начат!"
  # Сообщение при начале первого ивента
  first-event-started: "&fВы принудительно начали первый ивент!"
  # Сообщение при окончании первого ивента
  first-event-stopped: "&fВы принудительно окончили первый ивент!"
  # Сообщение при начале второго ивента
  second-event-started: "&fВы принудительно начали второй ивент!"
  # Сообщение при окончании второго ивента
  second-event-stopped: "&fВы принудительно окончили второй ивент!"
  # Сообщение при вводе неверного названия ивента
  incorrect-event: "&cНекорректное название ивента! Существует только first/second"
  # Хелп-сообщение
  help:
    - ""
    - "&fПомощь по плагину &6AFKillEvents&f:"
    - ""
    - "&6/afkillevents reload &f- перезагрузить конфигурацию"
    - "&6/afkillevents start first/second &f- начать ивент принудительно"
    - "&6/afkillevents stop first/second &f- окончить ивент принудительно"
    - ""