name: AFKillEvents
version: '${project.version}'
main: ru.anton_flame.afkillevents.AFKillEvents
api-version: '1.16'
softdepend: [PlaceholderAPI]
authors: [anton_flame]
commands:
  afkillevents:
    aliases:
      - afke